[package]
name = "trace_escrow_ledger_object"
version = "0.0.1"
edition = "2024"
description = "A Smart Escrow that accesses and traces every field in an `Escrow` ledger object."
license = "ISC"


[lib]
crate-type = ["cdylib"]


[dependencies]
xrpl-std = { path = "../../xrpl-std" }
