[package]
edition = "2024"
name = "xrpl-std"
version = "0.0.1"

# This empty workspace definition keeps this project independent of the parent workspace
[workspace]

[lib]
crate-type = ["lib"]

[dependencies]
log = "0.4.27"
