[package]
name = "xrpl-std"
version = "0.1.0"
edition = "2024"

# This empty workspace definition keeps this project independent of the parent workspace
[workspace]

[lib]
crate-type = ["lib"]

[dependencies]
