# Documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Main workspace and craft CLI tool
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 7

  # xrpl-std library
  - package-ecosystem: "cargo"
    directory: "/xrpl-std"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 7

  # wasm-host
  - package-ecosystem: "cargo"
    directory: "/wasm-host"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 7
