[workspace]
members = [".", "wasm-host"]

[package]
name = "craft"
version = "0.4.0"
edition = "2024"
description = "An interactive CLI tool for building and testing WASM smart contracts"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
inquire = "0.7.5"
colored = "2.2.0"
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
which = "7.0.3"
hex = "0.4"
walkdir = "2.4"
regex = "1.10"
sha2 = "0.10"
ripemd = "0.1"
bs58 = "0.5" 
open = "5.3.2"
