[workspace]
members = ["."]

[package]
name = "craft"
version = "0.3.0"
edition = "2024"
description = "An interactive CLI tool for building and testing WASM smart contracts"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
inquire = "0.6"
colored = "2.1"
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
which = "5.0"
hex = "0.4"
walkdir = "2.4"
regex = "1.10" 