[workspace]
members = [".", "wasm-host"]
#exclude = [
#    "wamr-rust-sdk/examples/wasi-hello",
#    "wamr-rust-sdk/resources/test/gcd",
#    "wamr-rust-sdk/resources/test/add-extra",
#    "wamr-rust-sdk/.devcontainer",
#    "wamr-rust-sdk/.github",
#]
[workspace.package]
edition = "2024"
license = "Apache-2.0"

[package]
name = "craft"
edition = "2024"
version = "0.5.0-devnet2"
description = "An interactive CLI tool for building and testing WASM smart contracts"

[dependencies]
anyhow = "1.0"
bs58 = "0.5"
clap = { version = "4.4", features = ["derive"] }
colored = "2.2.0"
hex = "0.4"
inquire = "0.7.5"
open = "5.3.2"
regex = "1.10"
ripemd = "0.1"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tokio = { version = "1.36", features = ["full"] }
walkdir = "2.4"
which = "7.0.3"
wamr-rust-sdk = {path = "./wamr-rust-sdk/"}
