[workspace]
members = [
    ".",
    "wasm-host"
]

[package]
name = "craft"
version = "0.5.0-devnet5"
edition = "2024"
description = "An interactive CLI tool for building and testing WASM smart contracts"

[dependencies]
anyhow = "1.0"
bs58 = "0.5"
clap = { version = "4.4", features = ["derive"] }
colored = "2.2.0"
docker-api = "0.14"
futures = "0.3"
hex = "0.4"
inquire = "0.7.5"
open = "5.3.2"
regex = "1.10"
reqwest = { version = "0.11", features = ["json"] }
ripemd = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1.36", features = ["full"] }
walkdir = "2.4"
which = "7.0.3"
