[workspace]

[package]
name = "host_functions_test"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
xrpl-std = { path = "../../xrpl-std" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"