[package]
name = "decoder_tests"
version = "0.0.1"
edition = "2024"
description = "Test the WASM host's ability to decode and access various ledger object fields."
license = "ISC"

[lib]
crate-type = ["cdylib"]

[dependencies]
xrpl-std = { path = "../../xrpl-std" }
