[package]
name = "kyc"
version = "0.1.0"
edition = "2024"
description = "A Smart Escrow that unlocks based on the presence of a certain credential."
license = "ISC"


[lib]
crate-type = ["cdylib"]


[dependencies]
xrpl-std = { path = "../../xrpl-std" }
