[package]
name = "trace_escrow_finish"
version = "0.0.1"
edition = "2024"
description = "A Smart Escrow that accesses and traces every field in the `EscrowFinish` transaction of a Smart Escrow."
license = "ISC"


[lib]
crate-type = ["cdylib"]


[dependencies]
xrpl-std = { path = "../../xrpl-std" }
