name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build documentation
        # the `--enable-index-page` flag creates an index.html file at the root of the docs
        # the `-Zunstable-options` flag is needed to use `--enable-index-page`
        run: RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --no-deps --workspace

      - name: Upload documentation files as artifact
        id: docs-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
          retention-days: 10

  deploy-docs-pages:
    permissions:
      id-token: write # Needed for OIDC authentication
      pages: write # this permission is needed for deploying into Github Pages
    environment:
      name: github-pages
      url: ${{ steps.docs-artifact.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-documentation
    # Deploy docs only pushes into the main branch
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Documentation to GitHub Pages
        id: docs-artifact
        uses: actions/deploy-pages@v4
